/**
 * Generates SQL UPDATE statements to fix scattered pins.
 * Run this locally, then paste the output into Supabase SQL Editor.
 */
const SUPABASE_URL = process.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = process.env.VITE_SUPABASE_ANON_KEY;
const MAPBOX_TOKEN = process.env.VITE_MAPBOX_TOKEN;

if (!SUPABASE_URL || !SUPABASE_KEY || !MAPBOX_TOKEN) {
  console.error('Missing env vars. Run with: node --env-file=.env --env-file=.env.local scripts/gen-fix-sql.mjs');
  process.exit(1);
}

const BBOX = { minLng: -80.8, minLat: 42.9, maxLng: -78.5, maxLat: 44.4 };
function isOutsideGTA(lat, lng) {
  return lat < BBOX.minLat || lat > BBOX.maxLat || lng < BBOX.minLng || lng > BBOX.maxLng;
}
function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

async function supaFetch(path) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
    headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}` },
  });
  return res.json();
}

async function geocode(address) {
  const url = `https://api.mapbox.com/geocoding/v5/mapbox.places/${encodeURIComponent(address)}.json?access_token=${MAPBOX_TOKEN}&types=address&limit=1&country=ca&proximity=-79.3832,43.6532&bbox=-80.8,42.9,-78.5,44.4`;
  const res = await fetch(url);
  const data = await res.json();
  if (data.features?.length > 0) {
    return { lat: data.features[0].center[1], lng: data.features[0].center[0] };
  }
  return null;
}

async function main() {
  console.error('Fetching events...');
  let allEvents = [];
  let offset = 0;
  while (true) {
    const batch = await supaFetch(`events?type=eq.KNOCK&select=event_id,payload&offset=${offset}&limit=1000`);
    if (!batch || batch.length === 0) break;
    allEvents = allEvents.concat(batch);
    if (batch.length < 1000) break;
    offset += 1000;
  }

  const scattered = [];
  for (const row of allEvents) {
    const p = typeof row.payload === 'string' ? JSON.parse(row.payload) : row.payload;
    if (!p.lat || !p.lng) continue;
    if (isOutsideGTA(parseFloat(p.lat), parseFloat(p.lng))) {
      scattered.push({ event_id: row.event_id, payload: p });
    }
  }

  console.error(`Found ${scattered.length} events outside GTA. Geocoding...`);

  // Output SQL header
  console.log('-- Fix scattered pins: re-geocode to GTA coordinates');
  console.log('-- Generated by scripts/gen-fix-sql.mjs');
  console.log('BEGIN;');
  console.log('');

  let fixed = 0;
  let failed = 0;

  for (let i = 0; i < scattered.length; i++) {
    const { event_id, payload } = scattered[i];
    const address = `${payload.house_number || ''} ${payload.street_name || ''}`.trim();
    if (!address) { failed++; continue; }

    try {
      const coords = await geocode(address);
      if (coords) {
        const updatedPayload = { ...payload, lat: coords.lat, lng: coords.lng };
        const jsonStr = JSON.stringify(updatedPayload).replace(/'/g, "''");
        console.log(`UPDATE public.events SET payload = '${jsonStr}'::jsonb WHERE event_id = '${event_id}';`);
        fixed++;
        console.error(`  [${i+1}/${scattered.length}] ${address} ✅`);
      } else {
        failed++;
        console.error(`  [${i+1}/${scattered.length}] ${address} ⚠️ no result`);
      }
    } catch (err) {
      failed++;
      console.error(`  [${i+1}/${scattered.length}] ${address} ❌ ${err.message}`);
    }
    await sleep(200);
  }

  console.log('');
  console.log('COMMIT;');
  console.error(`\nDone. Fixed: ${fixed}, Failed: ${failed}`);
  console.error('Copy the SQL output and run it in your Supabase SQL Editor.');
}

main().catch(err => { console.error(err); process.exit(1); });
